version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mqtt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mqtt_user
      POSTGRES_PASSWORD: Vik159753  
      POSTGRES_DB: mqtt
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mqtt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mqtt_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  mqtt:
    build: .  # ← ВАЖНО: Сборка из вашего Dockerfile, а не готовый образ
    container_name: mqtt_cont
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
