services:
  mariadb:
    image: mariadb:10.6
    container_name: mqtt_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword123!
      MARIADB_DATABASE: mqtt_auth
      MARIADB_USER: mqtt_user
      MARIADB_PASSWORD: MqttSecurePass123!
      MARIADB_ROOT_HOST: '%'  # Разрешаем подключения с любого хоста
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - mqtt_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MARIADB_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    build: ./plugins
    container_name: mqtt_cont
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - mqtt_network
    restart: unless-stopped

networks:
  mqtt_network:
    driver: bridge
    