# Основные настройки
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
allow_anonymous false

# Подключаем Go-плагин
auth_plugin /mosquitto/plugins/go-auth.so

# Включаем MySQL бэкенд (работает и с MariaDB!)
auth_opt_backends mysql

# Настройки подключения к MariaDB
auth_opt_mysql_host mariadb
auth_opt_mysql_port 3306
auth_opt
